# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

FLAVOR = ENV['FLAVOR']
PREFIX = ENV['PREFIX']
USER_PERFORM = ENV['USER_PERFORM']
BRANCH_NAME = ENV['BRANCH_NAME']
COMMIT_TITLE = ENV['COMMIT_TITLE']
APP_NAME = ENV['APP_ANDROID_NAME']

BUILD_PATH_DEFAULT = "build/app/outputs/flutter-apk/app-#{PREFIX}-release.apk"
GRADLE_PATH = './android'

platform :android do
  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end

    desc "Send Build Android Version #{FLAVOR}"
    lane :sendBuildToGoogleChat do
       diawi( token: ENV['DIAWI_TOKEN'],file: "#{BUILD_PATH_DEFAULT}")
       google_chat(
             webhook: ENV['GOOGLE_CHAT_URL'],
             title: "Build Android #{FLAVOR}",
             description: "Perform by #{USER_PERFORM}",
             buttonTitle: "DOWNLOAD",
             section1Title:"Branch #{BRANCH_NAME}",
             section1Description:"Commit #{COMMIT_TITLE}",
             buttonUrl: lane_context[SharedValues::UPLOADED_FILE_LINK_TO_DIAWI],
             imageUrl:  ENV['IMAGE_URL']
           )
    end

     desc "Build Android Version Local"
        lane :buildAndroidLocal do
           gradle(task: "clean assemble#{FLAVOR}Release",project_dir: GRADLE_PATH)
           diawi( token: ENV['DIAWI_TOKEN'],file: "#{BUILD_PATH_DEFAULT}")
           google_chat(
                 webhook: ENV['GOOGLE_CHAT_URL'],
                 title: 'Build Android Dev',
                 description: 'Perform in local',
                 buttonTitle: "DOWNLOAD #{APP_NAME}",
                 section1Title:"Branch #{BRANCH_NAME}",
                 section1Description:"Commit #{COMMIT_TITLE}",
                 buttonUrl: lane_context[SharedValues::UPLOADED_FILE_LINK_TO_DIAWI],
                 imageUrl: ENV['IMAGE_URL']
               )
        end

     desc "Distribute To Firebase"
        lane :distribute do
          firebase_app_distribution(
            app: ENV['FIREBASE_APP_ID'],
            groups: "testers",
            apk_path: "#{BUILD_PATH_DEFAULT}",
            firebase_cli_token: ENV['FIREBASE_TOKEN']
          )
        end
end
